apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  labels:
    app: frontend
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  stripPrefix:
    prefixes:
      - /argocd
  rules:
  - http:
      paths:
      - path: /argocd
        pathType: Prefix
        backend:
          service:
            name: frontend
            port: 
              number: 80
