apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: frontend
spec:
  project: default
  source:
    repoURL: https://github.com/littledevel/k3dargo.git
    targetRevision: HEAD 
    path: applications/business/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: true 
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff: 
        duration: 5s
        factor: 2
        maxDuration: 3m
