apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: db-ingress
  labels:
    app: db
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /db
        pathType: Prefix
        backend:
          service:
            name: db
            port: 
              number: 80

